"""RFC 4918 compliant WebDAV client, built on ``requests``."""

from webdav.api import (
    delete,
    get,
    head,
    lock,
    mkcol,
    options,
    propfind,
    proppatch,
    put,
    request,
    unlock,
)
from webdav.exceptions import (
    ClientError,
    ForbiddenError,
    HTTPStatusError,
    InsecureConfigurationError,
    InsufficientStorageError,
    IsACollectionError,
    IsAResourceError,
    LockError,
    MalformedResponseError,
    MultiStatusError,
    RedirectNotFollowedError,
    ResourceAlreadyExistsError,
    ResourceConflictError,
    ResourceLockedError,
    ResourceNotFoundError,
    TLSConfigError,
    WebDAVError,
)

# ``open`` mirrors FileSystem.open (like ``gzip.open`` / ``io.open``), so it is
# public and, as in those modules, ``from webdav import *`` shadows the builtin.
# pylint: disable-next=redefined-builtin
from webdav.fs import (
    FileSystem,
    content_language,
    content_length,
    content_type,
    copy,
    created,
    dav_compliance,
    download_file,
    download_fileobj,
    etag,
    exists,
    get_props,
    info,
    isdir,
    isfile,
    locked,
    ls,
    mkdir,
    modified,
    move,
    open,  # noqa: A004
    refresh_lock,
    remove,
    set_props,
    upload_file,
    upload_fileobj,
    walk,
)
from webdav.resource import Resource
from webdav.response import Response
from webdav.session import Session
from webdav.transport.redirects import RedirectPolicy

__version__ = "0.1.0"


__all__ = [
    "ClientError",
    "FileSystem",
    "ForbiddenError",
    "HTTPStatusError",
    "InsecureConfigurationError",
    "InsufficientStorageError",
    "IsACollectionError",
    "IsAResourceError",
    "LockError",
    "MalformedResponseError",
    "MultiStatusError",
    "RedirectNotFollowedError",
    "RedirectPolicy",
    "Resource",
    "ResourceAlreadyExistsError",
    "ResourceConflictError",
    "ResourceLockedError",
    "ResourceNotFoundError",
    "Response",
    "Session",
    "TLSConfigError",
    "WebDAVError",
    "__version__",
    "content_language",
    "content_length",
    "content_type",
    "copy",
    "created",
    "dav_compliance",
    "delete",
    "download_file",
    "download_fileobj",
    "etag",
    "exists",
    "get",
    "get_props",
    "head",
    "info",
    "isdir",
    "isfile",
    "lock",
    "locked",
    "ls",
    "mkcol",
    "mkdir",
    "modified",
    "move",
    "open",
    "options",
    "propfind",
    "proppatch",
    "put",
    "refresh_lock",
    "remove",
    "request",
    "set_props",
    "unlock",
    "upload_file",
    "upload_fileobj",
    "walk",
]
