"""Regenerate the file-system half of ``src/webdav/api.py`` from ``Session``.

``webdav.<name>`` must have the very parameters (and return type) of
``Session.<name>``, so those functions are not written by hand: this script reads
the ``Session`` class of ``src/webdav/session.py`` and writes one module-level
function per file-system operation into everything below the marker line in
``src/webdav/api.py``. The part above the marker (options, helpers, the verbs) is
hand-written and left alone.

    python tools/gen_api.py           # rewrite api.py (needs black installed)
    python tools/gen_api.py --check   # exit 1 if api.py is out of date (for CI)

``tests/test_api_consistency.py`` fails as well when the two drift apart.
"""

import ast
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SESSION = ROOT / "src" / "webdav" / "session.py"
API = ROOT / "src" / "webdav" / "api.py"
MARKER = "# --- generated by tools/gen_api.py from Session; do not edit below this line ---\n"

#: One-shot functions: open a session, run the method, close the session.
OPERATIONS = [
    "ls",
    "info",
    "exists",
    "isdir",
    "isfile",
    "mkdir",
    "remove",
    "get_props",
    "set_props",
    "refresh_lock",
    "content_length",
    "created",
    "modified",
    "etag",
    "content_type",
    "content_language",
    "dav_compliance",
    "walk",
    "download_file",
    "upload_file",
    "download_fileobj",
    "upload_fileobj",
]
#: The same, as context managers: the session stays open for the block.
CONTEXT_MANAGERS = ["open", "locked"]


def _is_overload(node: ast.FunctionDef) -> bool:
    return any(ast.unparse(d).startswith("overload") for d in node.decorator_list)


def _emit(node: ast.FunctionDef, *, context: bool, stub: bool) -> str:
    name = node.name
    args = node.args
    kwonly = [a.arg for a in args.kwonlyargs]
    # Options that are also a parameter of the function cannot be given twice.
    if "headers" in kwonly:
        options = "_UploadOptions"
    elif "chunk_size" in kwonly:
        options = "_TransferOptions"
    else:
        options = "_Options"
    positional = [a.arg for a in args.args[1:]]
    signature = ast.unparse(
        ast.arguments(
            posonlyargs=[],
            args=args.args[1:],
            vararg=None,
            kwonlyargs=args.kwonlyargs,
            kw_defaults=args.kw_defaults,
            kwarg=ast.arg("kwargs", ast.Name(f"Unpack[{options}]")),
            defaults=args.defaults,
        )
    )
    returns = ast.unparse(node.returns) if node.returns else "None"
    prefix = "@contextmanager\n" if context else ""
    # ``open`` shadows the builtin on purpose; the comment sits right after the
    # bracket, where black leaves it.
    noqa = "  # noqa: A001\n    " if name == "open" else ""
    if stub:
        return f"@overload\n{prefix}def {name}({noqa}{signature}) -> {returns}: ...\n"
    reference = f'"{name}"' if context else f"Session.{name}"
    call = ", ".join([reference, "kwargs", *positional, *[f"{k}={k}" for k in kwonly]])
    summary = (ast.get_docstring(node) or "").strip().splitlines()[0]
    if context:
        body = f"    with _context({call}) as value:\n        yield value"
    elif name == "walk":
        body = f"    return _walk({call})"
    elif returns == "None":
        body = f"    _run({call})"
    else:
        body = f"    return _run({call})"
    doc = (
        f'    """{summary}\n\n'
        f"    See :meth:`webdav.session.Session.{name}`; ``path`` is a full URL.\n"
        '    """'
    )
    return f"{prefix}def {name}({noqa}{signature}) -> {returns}:\n{doc}\n{body}\n"


def generate() -> str:
    """The generated functions, as source text (not yet formatted)."""
    tree = ast.parse(SESSION.read_text())
    session = next(
        n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "Session"
    )
    methods: dict[str, list[ast.FunctionDef]] = {}
    for node in session.body:
        if isinstance(node, ast.FunctionDef):
            methods.setdefault(node.name, []).append(node)
    parts = []
    for name in [*OPERATIONS, *CONTEXT_MANAGERS]:
        context = name in CONTEXT_MANAGERS
        overloads = [m for m in methods[name] if _is_overload(m)]
        (implementation,) = [m for m in methods[name] if not _is_overload(m)]
        parts += [_emit(m, context=context, stub=True) for m in overloads]
        parts.append(_emit(implementation, context=context, stub=False))
    return "\n\n".join(parts)


def build() -> str:
    """The whole new ``api.py``, formatted with black."""
    current = API.read_text()
    head = current.split(MARKER)[0].rstrip("\n") + "\n\n\n" + MARKER + "\n"
    text = head + generate()
    with tempfile.TemporaryDirectory() as tmp:
        target = Path(tmp) / "api.py"
        target.write_text(text)
        subprocess.run(
            [
                sys.executable,
                "-m",
                "black",
                "-q",
                "--config",
                str(ROOT / "pyproject.toml"),
                str(target),
            ],
            check=True,
        )
        return re.sub(
            r"\n{3,}(?=" + re.escape(MARKER) + ")", "\n\n\n", target.read_text()
        )


def main() -> int:
    """Rewrite ``api.py``, or with ``--check`` only report whether it is current."""
    new = build()
    if "--check" in sys.argv:
        if API.read_text() != new:
            sys.stderr.write("src/webdav/api.py is out of date: run tools/gen_api.py\n")
            return 1
        return 0
    API.write_text(new)
    return 0


if __name__ == "__main__":
    sys.exit(main())
